version: '3.5'
name: drmaatic-prod

services:
  drmaatic:
    image: drmaatic-dev:latest
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    command: [ "runserver" ]
    container_name: drmaatic
    env_file:
      - ../../settings/.env
      - .dev.env
    ports:
      - "8301:8300"
    volumes:
      - type: bind
        source: slurm.conf
        target: /etc/slurm/slurm.conf
      - type: bind
        source: slurmdbd.conf
        target: /etc/slurm/slurmdbd.conf
      - slurm_jobdir:/data
    extra_hosts:
      - "perse:172.21.2.90"

volumes:
  slurm_jobdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../tests
