name: drmaatic-slurm-cluster

services:
  mysql:
    image: mariadb:latest
    hostname: mysql
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: pwd
      MARIADB_DATABASE: slurm_acct_db
      MARIADB_USER: slurm
      MARIADB_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
#      PMA_USER: slurm
#      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    links:
      - mysql

  slurmdbd:
    image: giovtorres/slurm-docker-cluster:latest
    command: [ "slurmdbd" ]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: giovtorres/slurm-docker-cluster:latest
    command: [ "slurmctld" ]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - slurmdbd

  c1:
    image: giovtorres/slurm-docker-cluster:latest
    command: [ "slurmd" ]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - slurmctld

  c2:
    image: giovtorres/slurm-docker-cluster:latest
    command: [ "slurmd" ]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    depends_on:
      - "slurmctld"

  drmaatic:
    depends_on:
      - slurmctld
    build:
      context: ../../
      dockerfile: docker/testing/Dockerfile
    command: [ "runserver" ]
    container_name: drmaatic
    env_file:
      - ../../settings/.env
      - .testing-docker.env
    ports:
      - "8301:8300"
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../tests
  var_lib_mysql:
  var_log_slurm:
