# Generated by Django 4.2.5 on 2023-09-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drmaatic', '0002_group_execution_token_regen_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='throttling_rate_sustained',
        ),
    ]
