# Generated by Django 4.2.5 on 2023-09-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drmaatic', '0003_remove_group_throttling_rate_sustained'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='execution_token_regen_time',
            new_name='_execution_token_regen_time',
        ),
    ]
