# Generated by Django 4.2.5 on 2023-10-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drmaatic', '0004_rename_execution_token_regen_time_group__execution_token_regen_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='drmaatic.group'),
        ),
    ]
