# Generated by Django 4.2.5 on 2023-10-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drmaatic', '0006_alter_job_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_output_visible',
            new_name='is_output_public',
        ),
    ]
