# Generated by Django 4.2.5 on 2023-10-06 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drmaatic', '0007_rename_is_output_visible_task_is_output_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drmaatic.queue'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='drmaatic.group'),
        ),
    ]
