# Generated by Django 3.1.2 on 2021-10-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, choices=[('any', 'Any'), ('int', 'Integer'), ('float', 'Float'), ('string', 'String'), ('bool', 'Bool'), ('file', 'File')], default='any', max_length=100)),
                ('default', models.CharField(max_length=1000)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
