# Generated by Django 3.1.2 on 2021-10-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='Script',
        ),
    ]
