version: '3.5'
name: drmaatic-prod

services:
  drmaatic:
    image: drmaatic-prod:latest
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    command: [ "runserver" ]
    container_name: drmaatic
    env_file:
      - ../../settings/.env
      - .prod.env
    ports:
      - "8301:8300"
    volumes:
      - type: bind
        source: slurm.conf
        target: /etc/slurm/slurm.conf
      - type: bind
        source: slurmdbd.conf
        target: /etc/slurm/slurmdbd.conf
      - scriptdir:/scripts
      - jobdir:/outputs
      - loggerdir:/logs
    extra_hosts:
      - "perse:172.21.2.90"

volumes:
  scriptdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/django/scripts/
  jobdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/local/webservers/jobs/drmaatic/
  loggerdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/local/webservers/logs/drmaatic/
