version: '3.5'
name: drmaatic-staging

services:
  drmaatic:
    image: drmaatic-staging:latest
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    command: [ "runserver" ]
    container_name: drmaatic-staging
    env_file:
      - ../../settings/.env
      - .staging.env
    ports:
      - "8301:80"
    volumes:
      - type: bind
        source: slurm.conf
        target: /etc/slurm-llnl/slurm.conf
      - type: bind
        source: slurmdbd.conf
        target: /etc/slurm-llnl/slurmdbd.conf
      - scriptdir:/home/django/scripts-dev/
      - jobdir:/var/local/webservers/jobs/drmaatic-dev/
      - loggerdir:/logs
    extra_hosts:
      - "perse:172.21.2.90"
    userns_mode: "host"

volumes:
  scriptdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/django/scripts-dev/
  jobdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/local/webservers/jobs/drmaatic-dev/
  loggerdir:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=172.21.2.101,nolock,soft,rw"
      device: ":/volume1/Idra/logs/test"
