name: Docker Compose Build and Push production image

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the action on

env:
  REGISTRY_URL: https://registry.biocomputingup.it
  IMAGE_NAME: registry.biocomputingup.it/ring-ui/ring-ui-prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to private Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin "$REGISTRY_URL"

    - name: Build and push Docker image
      run: |
        docker build --build-arg NPM_BUILD_COMMAND=build-prod --tag $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:latest
        VERSION=$(git rev-list main | wc -l)
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION
        docker push $IMAGE_NAME:$VERSION
