name: Docker Compose Build and Push staging image

on:
  push:
    branches:
      - dev  # or any other branch you want to trigger the action on

env:
  REGISTRY_URL: https://registry.biocomputingup.it
  IMAGE_NAME: registry.biocomputingup.it/drmaatic/drmaatic-staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to private Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin "$REGISTRY_URL"

    - name: Build and push Docker image
      run: |
        docker build --tag $IMAGE_NAME:staging-latest -f docker/deploy/Dockerfile .
        docker push $IMAGE_NAME:staging-latest
        VERSION=$(git describe --always)
        docker tag $IMAGE_NAME:staging-latest $IMAGE_NAME:$VERSION
        docker push $IMAGE_NAME:$VERSION
